<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="2.9.0-beta.1" />
    <PackageReference Include="Azure.AI.Projects" Version="2.1.0-beta.4" />
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.5.1" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.16" />
    <PackageReference Include="WolverineFx" Version="6.23.0" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" Version="6.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AISocInvestigator.Application\AISocInvestigator.Application.csproj" />
    <ProjectReference Include="..\AISocInvestigator.Infrastructure\AISocInvestigator.Infrastructure.csproj" />
  </ItemGroup>

</Project>
